# docker-compose.yml
services:
  db:
    image: mysql:8.4.0
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - web
    networks:
      - backend
      - frontend


volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  backend:
  frontend:
