# Generated by Django 4.2.11 on 2024-06-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_desc_user_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
