# Generated by Django 4.2.11 on 2024-06-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'published')], default=0),
        ),
    ]
